// Bootstrap CSS
import "bootstrap/dist/css/bootstrap.min.css";
// Toastify Css
import "react-toastify/dist/ReactToastify.css";
// Global Style
import "@styles/global.scss";
import { Footer, Header } from "@components/parts";
import { navItems } from "@utils/data";
import Link from "next/link";

export const metadata = {
  title: "STB Cash Merchant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="pageContainer">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
